lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
mathjax: true
markdown: kramdown
title: Grundpraktikum Theoretische Chemie
gist:
  noscript: false
remote_theme: "jekyll/minima@1e8a445"
minima:
  social_links:
    - title: Liedl Lab Homepage
      icon: github
      url: "https://liedllab.org/"
  author:
    name: Lukas Meinschad & Jonas Schlagin
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-mathjax
