lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
mathjax: true
markdown: kramdown
title: Grundpraktikum Theoretische Chemie
gist:
  noscript: false
remote_theme: "jekyll/minima@1e8a445"
minima:
  nav_pages:
    - Optimierung.md 
    - Frequenzberechnung.md 
    - Potentialhyperflaeche.md
    - Thermodynamik.md
    - Linux-Tutorial.md 
    - Orca_Tipps.md
  social_links:
    - title: Practical Course Github
      icon: github
      url: "https://github.com/liedllab/practical_course_bachelor"
  author:
    name: Lukas Meinschad & Jonas Schlagin
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-mathjax
